import React,{useMemo,useState}from"react";
import{Activity,AlertTriangle,ArrowDownLeft,ArrowUpRight,BarChart3,Bell,Check,ChevronRight,Clock3,CreditCard,Database,Download,Filter,Gift,Leaf,LogOut,Menu,RefreshCw,Search,ShieldAlert,ShieldCheck,SlidersHorizontal,Users,WalletCards,X,Zap}from"lucide-react";
import"./admin-v10.css";

const USERS=[
{id:"782451963",name:"Василий",username:"optimist",vip:3,balance:1284.5,status:"active",joined:"06 Sep 2026",referrals:24,risk:"low"},
{id:"741928304",name:"Alex",username:"alex_oolong",vip:3,balance:842.2,status:"active",joined:"05 Sep 2026",referrals:8,risk:"low"},
{id:"663810227",name:"Maria",username:"maria_leaf",vip:2,balance:431.8,status:"active",joined:"04 Sep 2026",referrals:5,risk:"medium"},
{id:"590174632",name:"Ivan",username:"ivan_tea",vip:1,balance:96.4,status:"blocked",joined:"02 Sep 2026",referrals:1,risk:"high"},
{id:"514882019",name:"Anna",username:"anna_puer",vip:4,balance:2760,status:"active",joined:"31 Aug 2026",referrals:17,risk:"low"}
];
const REQUESTS=[
{id:"WD-1048",type:"withdraw",user:"782451963",name:"Василий",amount:246,network:"USDT TRC-20",date:"06 Sep · 18:42",status:"pending",risk:"low"},
{id:"WD-1047",type:"withdraw",user:"663810227",name:"Maria",amount:180,network:"USDT BEP-20",date:"06 Sep · 17:31",status:"pending",risk:"medium"},
{id:"DP-2041",type:"deposit",user:"741928304",name:"Alex",amount:500,network:"USDT TRC-20",date:"06 Sep · 16:58",status:"review",risk:"low"},
{id:"WD-1043",type:"withdraw",user:"590174632",name:"Ivan",amount:420,network:"Polygon",date:"06 Sep · 15:12",status:"blocked",risk:"high"}
];
const PLANS=[{id:1,name:"Сборщик Чая",amount:150,rate:2.5,days:20},{id:2,name:"Мастер Листа",amount:500,rate:2.5,days:25},{id:3,name:"Хранитель Улуна",amount:1000,rate:2.5,days:30},{id:4,name:"Владыка Пуэра",amount:2500,rate:2.5,days:35},{id:5,name:"Чайный Император",amount:5000,rate:2.5,days:40}];
const money=n=>`$${Number(n).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function AdminPage(){
 const[section,setSection]=useState("overview"),[query,setQuery]=useState(""),[requests,setRequests]=useState(REQUESTS),[users,setUsers]=useState(USERS),[notice,setNotice]=useState(""),[selected,setSelected]=useState(null),[menu,setMenu]=useState(false);
 const filtered=useMemo(()=>users.filter(u=>(u.name+u.username+u.id).toLowerCase().includes(query.toLowerCase())),[users,query]);
 const toast=x=>{setNotice(x);setTimeout(()=>setNotice(""),1800)};
 const act=(id,status)=>{setRequests(r=>r.map(x=>x.id===id?{...x,status}:x));toast(status==="approved"?"Операция одобрена":"Операция отклонена")};
 const nav=(id)=>{setSection(id);setMenu(false)};
 const stats=[{label:"Users",value:"1,284",delta:"+8.4%",icon:Users},{label:"Active VIP",value:"742",delta:"+5.2%",icon:Leaf},{label:"Pending withdrawals",value:"12",delta:"Needs review",icon:ArrowUpRight},{label:"Risk alerts",value:"3",delta:"2 high",icon:ShieldAlert}];
 const side=[ ["overview","Overview",BarChart3],["users","Users",Users],["vip","VIP plans",Leaf],["deposits","Deposits",ArrowDownLeft],["withdrawals","Withdrawals",ArrowUpRight],["referrals","Referrals",Users],["harvest","Harvest",Clock3],["spin","Lucky Spin",Gift],["antifraud","Anti-fraud",ShieldAlert],["support","Support",Bell],["settings","Settings",SlidersHorizontal] ];
 return <div className="admin-app">
  <aside className={`admin-sidebar ${menu?"open":""}`}>
   <div className="admin-brand"><span><Leaf size={19}/></span><div><b>TEA ROAD</b><small>ADMIN CONSOLE</small></div><button onClick={()=>setMenu(false)}><X size={17}/></button></div>
   <div className="admin-demo"><ShieldCheck size={14}/> DEMO ADMIN · real operations disabled</div>
   <nav>{side.map(([id,label,Icon])=><button className={section===id?"active":""} onClick={()=>nav(id)} key={id}><Icon size={17}/><span>{label}</span>{["withdrawals","antifraud","support"].includes(id)&&<em>{id==="withdrawals"?12:id==="antifraud"?3:4:0}</em>}<ChevronRight size={14}/></button>)}</nav>
   <div className="admin-side-bottom"><div className="admin-user"><div className="admin-avatar">A</div><div><b>Administrator</b><small>Super admin · demo</small></div></div><button onClick={()=>location.href="./"}><LogOut size={16}/> Back to Tea Road</button></div>
  </aside>
  <main className="admin-main">
   <header className="admin-top"><button className="admin-menu-btn" onClick={()=>setMenu(true)}><Menu size={19}/></button><div><span>JADE VALLEY · CONTROL ROOM</span><h1>{side.find(x=>x[0]===section)?.[1]||"Overview"}</h1></div><div className="admin-top-actions"><div className="admin-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search users, IDs..."/></div><button onClick={()=>toast("No new critical notifications")}><Bell size={17}/><i>3</i></button><button onClick={()=>toast("Dashboard refreshed")}><RefreshCw size={17}/></button></div></header>
   {section==="overview"&&<Overview stats={stats} nav={nav} toast={toast} requests={requests}/>} 
   {section==="users"&&<UsersPage users={filtered} setUsers={setUsers} selected={selected} setSelected={setSelected} toast={toast}/>} 
   {section==="vip"&&<VipAdmin toast={toast}/>} 
   {section==="deposits"&&<Operations title="Deposits" rows={requests.filter(x=>x.type==="deposit")} action={act} toast={toast}/>} 
   {section==="withdrawals"&&<Operations title="Withdrawals" rows={requests.filter(x=>x.type==="withdraw")} action={act} toast={toast}/>} 
   {section==="referrals"&&<Referrals/>}
   {section==="harvest"&&<HarvestAdmin toast={toast}/>} 
   {section==="spin"&&<SpinAdmin toast={toast}/>} 
   {section==="antifraud"&&<AntiFraud users={users} toast={toast}/>} 
   {section==="support"&&<SupportAdmin toast={toast}/>} 
   {section==="settings"&&<SettingsAdmin toast={toast}/>} 
  </main>{notice&&<div className="admin-toast"><Check size={16}/>{notice}</div>}
 </div>
}

function Overview({stats,nav,toast,requests}){return <div className="admin-content"><div className="admin-kpis">{stats.map(({label,value,delta,icon:Icon})=><article key={label}><div className="kpi-icon"><Icon size={18}/></div><span>{label}</span><b>{value}</b><small>{delta}</small></article>)}</div><div className="admin-grid-2"><section className="admin-card chart-card"><div className="card-head"><div><span>PLATFORM ACTIVITY</span><h2>Tea Road volume</h2></div><button onClick={()=>toast("Period set to 30 days")}>30 days <ChevronRight size={14}/></button></div><div className="fake-chart"><div className="chart-grid"/><div className="chart-line"><i/><i/><i/><i/><i/><i/></div><div className="chart-labels"><span>W1</span><span>W2</span><span>W3</span><span>W4</span></div></div></section><section className="admin-card"><div className="card-head"><div><span>OPERATIONS</span><h2>Queue requiring attention</h2></div><button onClick={()=>nav("withdrawals")}>View all <ChevronRight size={14}/></button></div><div className="queue">{requests.slice(0,4).map(r=><div key={r.id}><span className={`op-icon ${r.type}`}><WalletCards size={15}/></span><div><b>{r.name} · {r.id}</b><small>{r.network} · {r.date}</small></div><strong>{money(r.amount)}</strong><em className={r.risk}>{r.risk}</em></div>)}</div></section></div><div className="admin-grid-3"><Mini title="VIP distribution" value="58%" sub="VIP 3–5" bars={[58,42,31,18,9]}/><Mini title="Harvest completion" value="87.4%" sub="today" bars={[42,55,68,74,87]}/><Mini title="Referral activity" value="+12.8%" sub="vs yesterday" bars={[28,37,43,51,64]}/></div></div>}
function Mini({title,value,sub,bars}){return <section className="admin-card mini-card"><span>{title}</span><div><b>{value}</b><small>{sub}</small></div><div className="mini-bars">{bars.map((x,i)=><i style={{height:`${x}%`}} key={i}/>)}</div></section>}
function UsersPage({users,setUsers,selected,setSelected,toast}){return <div className="admin-content"><div className="admin-toolbar"><div><span>USER MANAGEMENT</span><h2>{users.length} users shown</h2></div><button className="admin-btn" onClick={()=>toast("CSV export prepared in demo mode")}> <Download size={15}/> Export</button></div><section className="admin-card table-card"><table><thead><tr><th>User</th><th>Telegram ID</th><th>VIP</th><th>Balance</th><th>Referrals</th><th>Risk</th><th>Status</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><div className="table-user"><span>{u.name.slice(0,1)}</span><div><b>{u.name}</b><small>@{u.username}</small></div></div></td><td className="mono">{u.id}</td><td><b className="vip-pill">VIP {u.vip}</b></td><td>{money(u.balance)}</td><td>{u.referrals}</td><td><em className={u.risk}>{u.risk}</em></td><td><em className={u.status}>{u.status}</em></td><td><button className="row-btn" onClick={()=>setSelected(u)}>Open</button></td></tr>)}</tbody></table></section>{selected&&<div className="admin-modal"><div className="admin-dialog"><button className="dialog-close" onClick={()=>setSelected(null)}><X/></button><span>USER PROFILE · {selected.id}</span><h2>{selected.name}</h2><div className="detail-grid"><div><small>Telegram ID</small><b>{selected.id}</b></div><div><small>Username</small><b>@{selected.username}</b></div><div><small>VIP</small><b>VIP {selected.vip}</b></div><div><small>Balance</small><b>{money(selected.balance)}</b></div><div><small>Referrals</small><b>{selected.referrals}</b></div><div><small>Risk</small><b>{selected.risk}</b></div></div><div className="dialog-actions"><button className="admin-btn" onClick={()=>toast("User balance adjustment opened")}>Adjust balance</button><button className="admin-btn danger" onClick={()=>{setUsers(x=>x.map(a=>a.id===selected.id?{...a,status:a.status==="blocked"?"active":"blocked"}:a));toast("User status changed");setSelected(null)}}>{selected.status==="blocked"?"Unblock":"Block user"}</button></div></div></div>}</div>}
function VipAdmin({toast}){return <div className="admin-content"><div className="admin-toolbar"><div><span>PRODUCT CONFIGURATION</span><h2>VIP plans</h2></div><button className="admin-btn" onClick={()=>toast("Plan editor opened")}> <SlidersHorizontal size={15}/> Edit settings</button></div><div className="plan-admin-grid">{PLANS.map(p=><article className="admin-card plan-admin" key={p.id}><div className="plan-top"><span>VIP {p.id}</span><b>{money(p.amount)}</b></div><h3>{p.name}</h3><div className="plan-metrics"><span><b>{p.rate}%</b><small>daily</small></span><span><b>{p.days}</b><small>days</small></span><span><b>{money(p.amount*p.rate/100)}</b><small>daily income</small></span></div><div className="plan-switch"><span>Available for users</span><i className="on"/></div><button onClick={()=>toast(`VIP ${p.id} editor opened`)}>Configure <ChevronRight size={14}/></button></article>)}</div></div>}
function Operations({title,rows,action,toast}){return <div className="admin-content"><div className="admin-toolbar"><div><span>TRANSACTION QUEUE</span><h2>{title}</h2></div><div className="toolbar-actions"><button className="admin-btn" onClick={()=>toast("Filters opened")}><Filter size={15}/> Filters</button><button className="admin-btn" onClick={()=>toast("Queue refreshed")}><RefreshCw size={15}/></button></div></div><section className="admin-card table-card"><table><thead><tr><th>ID</th><th>User</th><th>Amount</th><th>Network</th><th>Date</th><th>Risk</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="mono">{r.id}</td><td><b>{r.name}</b><small className="block">{r.user}</small></td><td><b>{money(r.amount)}</b></td><td>{r.network}</td><td>{r.date}</td><td><em className={r.risk}>{r.risk}</em></td><td><em className={r.status}>{r.status}</em></td><td><div className="inline-actions">{r.status!=="approved"&&r.status!=="blocked"&&<><button onClick={()=>action(r.id,"approved")}>Approve</button><button className="reject" onClick={()=>action(r.id,"blocked")}>Reject</button></>}</div></td></tr>)}</tbody></table></section></div>}
function Referrals(){return <div className="admin-content"><div className="admin-kpis"><Mini title="Level 1" value="642" sub="5%" bars={[42,55,61,73,80]}/><Mini title="Level 2" value="1,486" sub="2%" bars={[31,48,54,65,74]}/><Mini title="Level 3" value="3,204" sub="1%" bars={[20,33,41,52,62]}/></div><section className="admin-card referral-map"><div className="card-head"><div><span>REFERRAL ENGINE</span><h2>Team performance</h2></div></div><div className="ref-flow"><div><b>Root</b><small>1,284 users</small></div><i/><div><b>Level 1 · 5%</b><small>642 active</small></div><i/><div><b>Level 2 · 2%</b><small>1,486 active</small></div><i/><div><b>Level 3 · 1%</b><small>3,204 active</small></div></div></section></div>}
function HarvestAdmin({toast}){return <div className="admin-content"><div className="admin-grid-3"><Mini title="Harvests today" value="2,841" sub="87.4% completed" bars={[48,62,58,74,87]}/><Mini title="Daily output" value="$71.0K" sub="demo ledger" bars={[35,49,63,70,82]}/><Mini title="Accelerations" value="184" sub="paid action events" bars={[18,30,42,58,67]}/></div><section className="admin-card"><div className="card-head"><div><span>HARVEST CONTROL</span><h2>Global mechanics</h2></div><button className="admin-btn" onClick={()=>toast("Harvest settings saved in demo")}>Save</button></div><div className="control-grid"><label>Timer duration<input defaultValue="04:00:00"/></label><label>Acceleration price<input defaultValue="$5.00"/></label><label>Daily rate cap<input defaultValue="2.5%"/></label><label>Missed day behavior<select defaultValue="No income"><option>No income</option><option>Carry forward</option></select></label></div></section></div>}
function SpinAdmin({toast}){return <div className="admin-content"><section className="admin-card"><div className="card-head"><div><span>REWARDS</span><h2>Lucky Spin · admin grants only</h2></div><button className="admin-btn" onClick={()=>toast("Grant spin dialog opened")}>Grant spins</button></div><div className="reward-list">{[["+1 Tea Point","32%"],["+3 Tea Points","28%"],["+5 Tea Points","20%"],["+10 Tea Points","14%"],["JACKPOT ×2","6%"]].map(x=><div key={x[0]}><Gift size={16}/><b>{x[0]}</b><span>{x[1]}</span><i><em style={{width:x[1]}}/></i></div>)}</div><div className="admin-note"><ShieldCheck size={16}/> Spins are not purchased by users. They are granted by an administrator.</div></section></div>}
function AntiFraud({users,toast}){const alerts=users.filter(u=>u.risk!=="low");return <div className="admin-content"><div className="admin-kpis"><Mini title="Risk engine" value="ONLINE" sub="24/7 rules" bars={[70,75,80,84,92]}/><Mini title="High risk" value="2" sub="users" bars={[18,22,24,18,15]}/><Mini title="Review queue" value="7" sub="events" bars={[35,48,42,56,61]}/></div><section className="admin-card"><div className="card-head"><div><span>ANTI-FRAUD</span><h2>Risk alerts</h2></div><button className="admin-btn" onClick={()=>toast("Risk rules refreshed")}>Refresh rules</button></div><div className="alert-list">{alerts.map(u=><div key={u.id}><span className={`alert-icon ${u.risk}`}><AlertTriangle size={17}/></span><div><b>{u.name} · {u.id}</b><small>{u.risk==="high"?"Withdrawal velocity / unusual activity":"Multiple device or referral signals"}</small></div><em className={u.risk}>{u.risk}</em><button onClick={()=>toast(`Review opened for ${u.name}`)}>Review</button></div>)}</div></section></div>}
function SupportAdmin({toast}){return <div className="admin-content"><section className="admin-card"><div className="card-head"><div><span>SUPPORT QUEUE</span><h2>Open tickets</h2></div><button className="admin-btn" onClick={()=>toast("Support queue refreshed")}>Refresh</button></div><div className="ticket-list">{[["#T-481","Maria","Wallet","Withdrawal question","12 min"],["#T-480","Alex","VIP","Plan activation","34 min"],["#T-479","Anna","Security","PIN reset","1 h"],["#T-478","Ivan","Account","Access review","2 h"]].map(x=><div key={x[0]}><span>{x[0]}</span><div><b>{x[1]} · {x[2]}</b><small>{x[3]}</small></div><small>{x[4]}</small><button onClick={()=>toast(`Ticket ${x[0]} opened`)}>Open</button></div>)}</div></section></div>}
function SettingsAdmin({toast}){return <div className="admin-content"><section className="admin-card"><div className="card-head"><div><span>SYSTEM SETTINGS</span><h2>Tea Road configuration</h2></div><button className="admin-btn" onClick={()=>toast("System settings saved")}>Save changes</button></div><div className="control-grid"><label>Default language<select defaultValue="RU"><option>RU</option><option>EN</option><option>CN</option></select></label><label>Default theme<select defaultValue="Dark"><option>Dark</option><option>Light</option></select></label><label>Telegram authentication<select defaultValue="Enabled"><option>Enabled</option><option>Disabled</option></select></label><label>Maintenance mode<select defaultValue="Off"><option>Off</option><option>On</option></select></label></div><div className="admin-note"><Database size={16}/> Telegram ID remains the primary user identifier. Transaction Password is a separate 6-digit PIN for withdrawal confirmation.</div></section></div>}
